Update docker-build-and-deploy.yml

diff --git a/.github/workflows/docker-build-and-deploy.yml b/.github/workflows/docker-build-and-deploy.yml
--- a/.github/workflows/docker-build-and-deploy.yml
+++ b/.github/workflows/docker-build-and-deploy.yml
@@ -76,13 +76,12 @@ jobs:
 
           # Deploy the application to the final remote host
           sshpass -p '${{ secrets.INTERMEDIATE_HOST_PASSWORD }}' ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${INTERMEDIATE_HOST} << 'EOF'
-            # Change to the application directory
-            cd ~/st125050-a3-car || exit
-            
-            # Pull the latest Docker image
+            echo "Changing to application directory..."
+            cd ~/st125050-a3-car || { echo "Directory not found! Exiting."; exit 1; }
+            echo "Pulling the latest Docker image..."
             docker pull st125050/a3car:latest
             
-            # Deploy using Docker Compose
+            echo "Deploying using Docker Compose..."
             docker-compose down || true
             docker-compose up -d
 
